name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Create .env file
        run: |
          echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
          echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
          echo POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env
          echo RPC_USER=${{ secrets.RPC_USER }} >> .env
          echo RPC_PASSWORD=${{ secrets.RPC_PASSWORD }} >> .env
          echo BITCOIN_RPC_USER=${{ secrets.BITCOIN_RPC_USER }} >> .env
          echo BITCOIN_RPC_PASSWORD=${{ secrets.BITCOIN_RPC_PASSWORD }} >> .env
          echo COINGECKO_URL=${{ secrets.COINGECKO_URL }} >> .env
          echo BITCOIN_RPC_ALLOW_IP=${{ secrets.BITCOIN_RPC_ALLOW_IP }} >> .env
          echo BITCOIN_RPC_PORT=${{ secrets.BITCOIN_RPC_PORT }} >> .env
          echo BITCOIN_PRUNE=${{ secrets.BITCOIN_PRUNE }} >> .env
          echo RPC_BIND=${{ secrets.RPC_BIND }} >> .env

      - name: Copy files to EC2
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@${{ secrets.EC2_PUBLIC_IP }}:/home/ubuntu/bitcoin_explorer

      - name: SSH into EC2 and run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_PUBLIC_IP }} \
          'cd /home/ubuntu/bitcoin_explorer && \
          docker-compose down && \
          docker-compose up -d --build'
